### PR TITLE
fix: fixed tagged error fn types

### LINKED ISSUE #594: Bug: Functions that work with tagged error fail at type level when non-tagged error present
Functions such as catchTag, etc. require that `E extends {_tag: string }` which is not always the case(e.g. when using `Error`). For example, the following fails:

```ts
const fails = pipe(
  Effect.fail<TestError | Error>(new TestError()),
  Effect.catchTag("TestError", () => Effect.succeed("")) // type error, Error doesn't extend { _tag: string }
);
```

The following is a more flexible type def:

```ts
<K extends (E extends { _tag: string } ? E["_tag"] : never), E>
```

It behaves identically for tagged errors while allowing non-tagged errors to pass through w/o type errors. 

https://codesandbox.io/p/sandbox/compassionate-shtern-lqt2l5

### PR DESCRIPTION
**Pull request by jessekelly881**
Fixes catchTag, catchTags, tapErrorTag type signatures. Closes #594

### CODE REVIEW

File: src/internal/effect.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import * as HashMap from "@effect/data/HashMap"
 import * as HashSet from "@effect/data/HashSet"
 import * as List from "@effect/data/List"
 import * as Option from "@effect/data/Option"
-import type { Predicate, Refinement } from "@effect/data/Predicate"
+import { isObject, type Predicate, type Refinement } from "@effect/data/Predicate"
```
Comment (tim-smart) [inline src/internal/effect.ts:11]: I think we should just use a namespace import here.

**Review by tim-smart — CHANGES_REQUESTED** [review]

File: src/internal/effect.ts (hunk 1 above)
Comment (jessekelly881) [reply src/internal/effect.ts]: Updated @tim-smart
